# Generated by Django 4.0.3 on 2022-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
