# Generated by Django 4.0.3 on 2022-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_tweet_content_alter_tweet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=999),
        ),
    ]
